import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import SessionProvider from "./components/SessionProvider"
import { getServerSession } from "next-auth";
import NavBar from "./components/Navbar";
=======

>>>>>>> b531f35337478b5a38f2f653027847524c4515f9
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<<<<<<< HEAD
export default  async function RootLayout({ children }) {

  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProvider session={session}>
        <NavBar/>
        {children}
        </SessionProvider>
        </body>
=======
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
>>>>>>> b531f35337478b5a38f2f653027847524c4515f9
    </html>
  );
}
